# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official Node.js LTS on Alpine
FROM node:lts-alpine

WORKDIR /app

# Install dependencies (including dev for build)
COPY package.json package-lock.json ./
RUN npm install

# Copy remaining source files
COPY . .

# Build the project
RUN npm run build

# Expose port 8081 for HTTP mode
EXPOSE 8081

# Set environment variable for HTTP mode
ENV TRANSPORT=http
ENV PORT=8081

# Entrypoint for MCP server in HTTP mode
ENTRYPOINT ["node", "dist/index.js"]
